export default function sitemap() {
  return [
  {
    url: 'https://www.neckhump.com/',
    lastModified: new Date('2025-10-22T12:00:00.000Z'),
    changeFrequency: 'weekly',
    priority: 1,
  },
  {
    url: 'https://www.neckhump.com/exercise-library',
    lastModified: new Date('2025-10-11T04:43:57.881Z'),
    changeFrequency: 'monthly',
    priority: 0.95,
  },
  {
    url: 'https://www.neckhump.com/neck-hump-exercises',
    lastModified: new Date('2025-10-11T05:06:56.271Z'),
    changeFrequency: 'monthly',
    priority: 0.95,
  },
  {
    url: 'https://www.neckhump.com/neck-hump-guide',
    lastModified: new Date('2025-10-11T04:59:08.232Z'),
    changeFrequency: 'monthly',
    priority: 0.95,
  },
  {
    url: 'https://www.neckhump.com/posture-correction-guide',
    lastModified: new Date('2025-10-11T04:59:08.230Z'),
    changeFrequency: 'monthly',
    priority: 0.95,
  },
  {
    url: 'https://www.neckhump.com/best-pillow-for-neck-hump',
    lastModified: new Date('2025-10-06T03:05:55.888Z'),
    changeFrequency: 'monthly',
    priority: 0.9,
  },
  {
    url: 'https://www.neckhump.com/best-neck-hump-corrector-pillows',
    lastModified: new Date('2025-10-22T12:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.9,
  },
  {
    url: 'https://www.neckhump.com/how-to-fix-posture-at-home',
    lastModified: new Date('2025-10-11T04:59:08.232Z'),
    changeFrequency: 'monthly',
    priority: 0.9,
  },
  {
    url: 'https://www.neckhump.com/how-to-get-rid-of-neck-hump-fast',
    lastModified: new Date('2025-10-23T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.95,
  },
  {
    url: 'https://www.neckhump.com/learn',
    lastModified: new Date('2025-10-11T04:50:10.029Z'),
    changeFrequency: 'weekly',
    priority: 0.9,
  },
  {
    url: 'https://www.neckhump.com/solutions',
    lastModified: new Date('2025-10-06T03:08:54.899Z'),
    changeFrequency: 'weekly',
    priority: 0.9,
  },
  {
    url: 'https://www.neckhump.com/how-to-sleep-with-neck-hump',
    lastModified: new Date('2025-10-06T03:01:01.007Z'),
    changeFrequency: 'monthly',
    priority: 0.85,
  },
  {
    url: 'https://www.neckhump.com/buffalo-hump-vs-neck-hump',
    lastModified: new Date('2025-10-06T03:06:07.748Z'),
    changeFrequency: 'monthly',
    priority: 0.8,
  },
  {
    url: 'https://www.neckhump.com/desk-setup-guide',
    lastModified: new Date('2025-10-06T03:01:01.006Z'),
    changeFrequency: 'monthly',
    priority: 0.8,
  },
  {
    url: 'https://www.neckhump.com/dowagers-hump-exercises',
    lastModified: new Date('2025-10-23T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.9,
  },
  {
    url: 'https://www.neckhump.com/dowagers-hump-vs-neck-hump',
    lastModified: new Date('2025-10-06T03:06:28.242Z'),
    changeFrequency: 'monthly',
    priority: 0.8,
  },
  {
    url: 'https://www.neckhump.com/ergonomic-workspace-neck-hump',
    lastModified: new Date('2025-10-06T03:03:08.019Z'),
    changeFrequency: 'monthly',
    priority: 0.8,
  },
  {
    url: 'https://www.neckhump.com/help',
    lastModified: new Date('2025-10-06T05:13:21.085Z'),
    changeFrequency: 'weekly',
    priority: 0.8,
  },
  {
    url: 'https://www.neckhump.com/military-neck-cervical-lordosis',
    lastModified: new Date('2025-10-06T03:05:14.283Z'),
    changeFrequency: 'monthly',
    priority: 0.8,
  },
  {
    url: 'https://www.neckhump.com/neck-hump-causes',
    lastModified: new Date('2025-10-11T04:29:15.832Z'),
    changeFrequency: 'monthly',
    priority: 0.8,
  },
  {
    url: 'https://www.neckhump.com/neck-hump-surgery-guide',
    lastModified: new Date('2025-10-06T03:31:08.913Z'),
    changeFrequency: 'monthly',
    priority: 0.8,
  },
  {
    url: 'https://www.neckhump.com/posture-exercises',
    lastModified: new Date('2025-10-06T03:06:48.190Z'),
    changeFrequency: 'monthly',
    priority: 0.8,
  },
  {
    url: 'https://www.neckhump.com/privacy',
    lastModified: new Date('2025-09-27T06:49:41.311Z'),
    changeFrequency: 'yearly',
    priority: 0.8,
  },
  {
    url: 'https://www.neckhump.com/tech-neck-prevention-guide',
    lastModified: new Date('2025-10-11T04:29:15.832Z'),
    changeFrequency: 'monthly',
    priority: 0.8,
  },
  {
    url: 'https://www.neckhump.com/terms',
    lastModified: new Date('2025-09-27T06:49:41.314Z'),
    changeFrequency: 'yearly',
    priority: 0.8,
  },
  {
    url: 'https://www.neckhump.com/text-neck-syndrome',
    lastModified: new Date('2025-10-06T03:03:08.019Z'),
    changeFrequency: 'monthly',
    priority: 0.8,
  },
  {
    url: 'https://www.neckhump.com/about/dr-sarah-johnson',
    lastModified: new Date('2025-10-11T04:29:15.832Z'),
    changeFrequency: 'yearly',
    priority: 0.7,
  },
  {
    url: 'https://www.neckhump.com/exercises/chin-tucks',
    lastModified: new Date('2025-10-22T12:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.7,
  },
  {
    url: 'https://www.neckhump.com/exercises/doorway-pec-stretch',
    lastModified: new Date('2025-10-22T12:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.7,
  },
  {
    url: 'https://www.neckhump.com/exercises/upper-back-foam-rolling',
    lastModified: new Date('2025-10-11T04:20:55.929Z'),
    changeFrequency: 'monthly',
    priority: 0.7,
  },
  {
    url: 'https://www.neckhump.com/exercises/wall-angels',
    lastModified: new Date('2025-10-22T12:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.7,
  },
  {
    url: 'https://www.neckhump.com/exercises/y-t-w-raises',
    lastModified: new Date('2025-10-22T12:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.7,
  },
  {
    url: 'https://www.neckhump.com/help/exercises-safety',
    lastModified: new Date('2025-10-06T05:13:21.085Z'),
    changeFrequency: 'monthly',
    priority: 0.75,
  },
  {
    url: 'https://www.neckhump.com/help/product-questions',
    lastModified: new Date('2025-10-11T04:20:55.912Z'),
    changeFrequency: 'monthly',
    priority: 0.75,
  },
  {
    url: 'https://www.neckhump.com/help/specific-situations',
    lastModified: new Date('2025-10-06T05:13:21.087Z'),
    changeFrequency: 'monthly',
    priority: 0.75,
  },
  {
    url: 'https://www.neckhump.com/help/timeline-questions',
    lastModified: new Date('2025-10-06T05:13:21.095Z'),
    changeFrequency: 'monthly',
    priority: 0.75,
  },
  {
    url: 'https://www.neckhump.com/help/troubleshooting',
    lastModified: new Date('2025-10-06T05:13:21.090Z'),
    changeFrequency: 'monthly',
    priority: 0.75,
  },
  {
    url: 'https://www.neckhump.com/help/exercises-safety/can-i-do-chin-tucks-with-herniated-disc',
    lastModified: new Date('2025-10-06T05:13:21.086Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/exercises-safety/exercises-safe-during-pregnancy',
    lastModified: new Date('2025-10-06T05:13:21.086Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/exercises-safety/forward-head-posture-after-whiplash',
    lastModified: new Date('2025-10-06T05:13:21.087Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/exercises-safety/forward-head-posture-with-arthritis',
    lastModified: new Date('2025-10-06T05:13:21.087Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/exercises-safety/neck-exercises-after-whiplash',
    lastModified: new Date('2025-10-06T05:13:21.085Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/exercises-safety/neck-exercises-with-arthritis',
    lastModified: new Date('2025-10-06T05:13:21.087Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/product-questions/best-ergonomic-chairs-neck-hump',
    lastModified: new Date('2025-10-06T05:13:21.095Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/product-questions/best-exercise-bands-neck-exercises',
    lastModified: new Date('2025-10-06T05:13:21.094Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/product-questions/best-pillow-back-sleepers',
    lastModified: new Date('2025-10-11T03:24:27.342Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/product-questions/side-sleeper-pillow-guide',
    lastModified: new Date('2025-01-21T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.7,
  },
  {
    url: 'https://www.neckhump.com/help/product-questions/budget-pillow-alternatives',
    lastModified: new Date('2025-10-06T05:13:21.093Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/product-questions/budget-pillow-alternatives-under-50',
    lastModified: new Date('2025-10-06T05:13:21.095Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/product-questions/cervical-traction-devices-comparison',
    lastModified: new Date('2025-10-11T04:20:55.904Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/product-questions/foam-roller-complete-guide',
    lastModified: new Date('2025-01-21T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.7,
  },
  {
    url: 'https://www.neckhump.com/help/product-questions/laptop-stands-better-posture',
    lastModified: new Date('2025-10-11T04:20:55.903Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/product-questions/memory-foam-vs-cervical-pillow',
    lastModified: new Date('2025-10-06T05:13:21.094Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/product-questions/posture-correctors-do-they-work',
    lastModified: new Date('2025-10-11T04:20:55.904Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/product-questions/standing-desk-setup-posture',
    lastModified: new Date('2025-10-11T04:20:55.903Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/specific-situations/neck-exercises-truck-drivers',
    lastModified: new Date('2025-10-11T04:20:55.910Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/specific-situations/neck-exercises-wheelchair-users',
    lastModified: new Date('2025-10-11T03:24:27.394Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/specific-situations/neck-hump-exercises-office-workers',
    lastModified: new Date('2025-10-11T03:24:27.314Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/specific-situations/neck-hump-exercises-pregnant-women',
    lastModified: new Date('2025-10-06T05:13:21.088Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/specific-situations/neck-hump-while-breastfeeding',
    lastModified: new Date('2025-10-06T05:13:21.088Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/specific-situations/posture-during-long-flights',
    lastModified: new Date('2025-10-06T05:09:21.225Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/specific-situations/posture-exercises-for-seniors',
    lastModified: new Date('2025-10-06T05:13:21.089Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/specific-situations/posture-exercises-healthcare-workers',
    lastModified: new Date('2025-10-11T04:20:55.904Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/specific-situations/posture-exercises-remote-workers',
    lastModified: new Date('2025-10-06T05:13:21.089Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/specific-situations/posture-exercises-seniors-over-65',
    lastModified: new Date('2025-10-06T05:13:21.088Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/timeline-questions/how-long-until-neck-hump-improves',
    lastModified: new Date('2025-10-06T05:13:21.096Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/timeline-questions/how-often-should-i-do-exercises',
    lastModified: new Date('2025-10-06T05:13:21.096Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/timeline-questions/realistic-timeline-severe-neck-hump',
    lastModified: new Date('2025-10-06T05:13:21.095Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/timeline-questions/when-to-increase-exercise-difficulty',
    lastModified: new Date('2025-10-06T05:13:21.096Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/troubleshooting/cant-feel-neck-muscles-working',
    lastModified: new Date('2025-10-11T04:20:55.908Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/troubleshooting/chin-tucks-causing-dizziness',
    lastModified: new Date('2025-10-06T05:13:21.091Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/troubleshooting/exercises-feel-too-easy',
    lastModified: new Date('2025-10-11T04:20:55.910Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/troubleshooting/exercises-making-neck-pain-worse',
    lastModified: new Date('2025-10-06T05:13:21.092Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/troubleshooting/headaches-after-posture-exercises',
    lastModified: new Date('2025-10-06T05:13:21.090Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/troubleshooting/neck-cracking-during-exercises',
    lastModified: new Date('2025-10-11T04:20:55.903Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/troubleshooting/neck-pain-after-sleeping',
    lastModified: new Date('2025-10-06T05:13:21.090Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/troubleshooting/neck-pain-when-looking-down',
    lastModified: new Date('2025-10-06T05:13:21.090Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/troubleshooting/neck-stiffness-after-exercises',
    lastModified: new Date('2025-10-06T05:13:21.092Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/troubleshooting/no-improvement-after-8-weeks',
    lastModified: new Date('2025-10-06T05:13:21.091Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/specific-situations/posture-exercises-students',
    lastModified: new Date('2025-01-15T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/specific-situations/neck-hump-exercises-athletes',
    lastModified: new Date('2025-01-15T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/exercises-safety/neck-exercises-for-osteoporosis',
    lastModified: new Date('2025-01-15T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/exercises-safety/chin-tucks-with-cervical-stenosis',
    lastModified: new Date('2025-01-15T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/exercises-safety/exercises-after-cervical-fusion',
    lastModified: new Date('2025-01-15T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/exercises-safety/posture-exercises-with-fibromyalgia',
    lastModified: new Date('2025-01-15T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/exercises-safety/neck-hump-correction-with-ms',
    lastModified: new Date('2025-01-15T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/exercises-safety/forward-head-posture-with-eds',
    lastModified: new Date('2025-01-15T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/troubleshooting/shoulder-pain-during-chin-tucks',
    lastModified: new Date('2025-01-15T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/troubleshooting/exercises-causing-numbness',
    lastModified: new Date('2025-01-15T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/timeline-questions/progress-tracking-methods',
    lastModified: new Date('2025-01-15T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/timeline-questions/plateau-periods-and-setbacks',
    lastModified: new Date('2025-01-15T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/timeline-questions/age-related-recovery-differences',
    lastModified: new Date('2025-01-15T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/timeline-questions/seasonal-and-lifestyle-impact',
    lastModified: new Date('2025-01-15T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/timeline-questions/when-to-seek-professional-help',
    lastModified: new Date('2025-01-15T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: 'https://www.neckhump.com/help/timeline-questions/long-term-maintenance-timeline',
    lastModified: new Date('2025-01-15T00:00:00.000Z'),
    changeFrequency: 'monthly',
    priority: 0.6,
  }
  ]
}
